<a href="https://colab.research.google.com/github/heejinChang/DataScience/blob/master/assignment11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np
import warnings
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
warnings.filterwarnings(action="ignore")
from sklearn.datasets import load_iris

#load iris data
iris = load_iris()

df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [2]:
X = df.loc[:, :'petal width (cm)'] # 
y = df['species']

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [4]:
# Train a DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)

# do bagging
bagging = BaggingClassifier(tree, n_estimators=10, random_state=42)
bagging.fit(X_train, y_train)

# Predict the labels using voting
y_pred = bagging.predict(X_test)

# Calculate accuracy using confusion matrix
conf_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n", conf_mat)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

Confusion Matrix: 
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
Accuracy:  0.9666666666666667
